name: Check

on:
  pull_request:
    branches:
      - $default-branch
  push:
    branches:
      - $default-branch
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the Makefile check rule in a docker container.
      run: docker-compose run check -j2 --output-sync check
